[package]
name = "ephemeris"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5"  # Already present for ReadBytesExt
serde = { version = "1.0", features = ["derive"] }  # Added for Serialize