/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_cryptokeypair_free: (a: number, b: number) => void;
export const cryptokeypair_public_key: (a: number) => [number, number];
export const cryptokeypair_private_key: (a: number) => [number, number];
export const __wbg_encrypteddata_free: (a: number, b: number) => void;
export const encrypteddata_ciphertext: (a: number) => [number, number];
export const encrypteddata_nonce: (a: number) => [number, number];
export const encrypteddata_classification: (a: number) => number;
export const encrypteddata_timestamp: (a: number) => bigint;
export const encrypteddata_signature: (a: number) => [number, number];
export const __wbg_socompqcryptocore_free: (a: number, b: number) => void;
export const socompqcryptocore_new: () => number;
export const socompqcryptocore_generate_key_pair: (a: number) => [number, number, number];
export const socompqcryptocore_encrypt: (a: number, b: number, c: number, d: number) => [number, number, number];
export const socompqcryptocore_decrypt: (a: number, b: number, c: number) => [number, number, number, number];
export const socompqcryptocore_hash_data: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const socompqcryptocore_get_audit_log: (a: number) => [number, number];
export const socompqcryptocore_clear_audit_log: (a: number) => void;
export const socompqcryptocore_is_initialized: (a: number) => number;
export const socompqcryptocore_version: (a: number) => [number, number];
export const socompqcryptocore_generate_random_bytes: (a: number, b: number) => [number, number, number, number];
export const main: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
